### ISSUE TITLE
Compile issues by gcc-13

### ISSUE THREAD

**Issue by jinzhezhang020** [compas/grasp#112]
Hi everyone

I meet a issues when using grasp, which compiled by gcc-13.

The server of my teammate was recently upgraded from Fedora 37 to 39. In Fedora 39, the default GCC compilation is gcc-13. We were able to successfully compile Grasp; however, we noticed some discrepancies between the example in the manual (6.5. Fifth Example: The Study of Energy Spectra for Ni XIV, Obtaining Unique Labels) and our own results.

## 1. rcsfinteract
We get different results from rcsfinteract with same command:
1. the result get from gcc-11 version, which is the same with the manual

```shell
 RCSFinteract: Determines all the CSFs (rcsf.inp) that interact
               with the CSFs in the multireference (rcsfmr.inp)
               (C)  Copyright by G. Gaigalas and Ch. F. Fischer
               (Fortran 95 version)               NIST  (2021).
               Input files: rcsfmr.inp, rcsf.inp
               Output file: rcsf.out

 Reduction based on Dirac-Coulomb (1) or
 Dirac-Coulomb-Breit (2) Hamiltonian?
2
 Loading Configuration Symmetry List File ...
 There are 16 relativistic subshells;
  Block    MR NCSF   Before NCSF   After NCSF
    1            8         1664         1047
    2           11         2837         1862
    3           10         3271         2112
    4            5         2972         1537
    5            2         2264          801

 Wall time:
        1 seconds

 Finish Date and Time:
   Date (Yr/Mon/Day): 2023/12/13
   Time (Hr/Min/Sec): 19/30/02.690
   Zone: +0800

 RCSFinteract: Execution complete.
```
2. the result get from gcc-13 version

```shell
 RCSFinteract: Determines all the CSFs (rcsf.inp) that interact
               with the CSFs in the multireference (rcsfmr.inp)
               (C)  Copyright by G. Gaigalas and Ch. F. Fischer
               (Fortran 95 version)               NIST  (2021).
               Input files: rcsfmr.inp, rcsf.inp
               Output file: rcsf.out

 Reduction based on Dirac-Coulomb (1) or
 Dirac-Coulomb-Breit (2) Hamiltonian?
2
 Loading Configuration Symmetry List File ...
 There are 16 relativistic subshells;
  Block    MR NCSF   Before NCSF   After NCSF
    1            8         1664         1142
    2           11         2837         2058
    3           10         3271         2362
    4            5         2972         1770
    5            2         2264          909

 Wall time:
        1 seconds

 Finish Date and Time:
   Date (Yr/Mon/Day): 2023/12/13
   Time (Hr/Min/Sec): 19/32/43.439
   Zone: +0800

 RCSFinteract: Execution complete.

```
## 2. rmchdf and rci
I applied the identical procedure as that of manual operation and obtained the following outcome:

1.the result get from gcc-11 version, which is the same with the manual

```shell
------------------------------------------------------------------------------------------
No  Pos  J   Parity  Energy Total  Levels          Splitting     Configuration
                      (a.u.)        (cm^-1)         (cm^-1)
------------------------------------------------------------------------------------------
1   1  3/2     -    -1443.2224318       0.00            0.00    2s(2).2p(6).3s(2).3p(3)4S3_4S
2   2  3/2     -    -1443.0055953   47590.12        47590.12    2s(2).2p(6).3s(2).3p(3)2D3_2D
3   1  5/2     -    -1442.9699841   55405.86         7815.74    2s(2).2p(6).3s(2).3p(3)2D3_2D
4   1  1/2     -    -1442.8231291   87636.81        32230.95    2s(2).2p(6).3s(2).3p(3)2P1_2P
5   3  3/2     -    -1442.7718374   98894.05        11257.25    2s(2).2p(6).3s(2).3p(3)2P1_2P
6   1  5/2     +    -1441.7819193  316155.95       217261.89    2s(2).2p(6).3s_2S.3p(4)3P2_4P
7   1  3/2     +    -1441.7163490  330546.97        14391.02    2s(2).2p(6).3s_2S.3p(4)3P2_4P
8   1  1/2     +    -1441.6893375  336475.31         5928.35    2s(2).2p(6).3s_2S.3p(4)3P2_4P
9   2  3/2     +    -1441.4303647  393313.26        56837.95    2s(2).2p(6).3s_2S.3p(4)1D2_2D
10  2  5/2     +    -1441.4141226  396877.99         3564.73    2s(2).2p(6).3s_2S.3p(4)1D2_2D
 .........
```

2. the result get from gcc-13 version

```shell
rlevels Ni_even_n4.cm Ni_odd_n4.cm                                                                 
 nblock =            5   ncftot =         8241   nw =           16   nelec =           15
 nblock =            3   ncftot =         1352   nw =           16   nelec =           15

 Energy levels for ...
 Rydberg constant is   109737.31569
 Splitting is the energy difference with the lower neighbor
------------------------------------------------------------------------------------------
 No Pos  J Parity Energy Total    Levels     Splitting     Configuration
                      (a.u.)      (cm^-1)     (cm^-1)
------------------------------------------------------------------------------------------
  1  1  5/2 +   -1521.6305278        0.00        0.00    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3P2_6D
  2  1  7/2 +   -1521.5555329    16459.47    16459.47    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3P2_6D
  3  1  3/2 +   -1521.3337119    65143.56    48684.09    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3P2_6P
  4  1  1/2 +   -1520.1621637   322268.67   257125.11    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3P2_4P
  5  2  5/2 +   -1519.9963675   358656.72    36388.05    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3P2_4D
  6  2  7/2 +   -1519.8619203   388164.47    29507.76    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3F2_4G
  7  2  3/2 +   -1519.7382993   415296.15    27131.67    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3F2_6F
  8  1  9/2 +   -1519.4806089   471852.64    56556.49    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3F2_6G
  9  3  5/2 +   -1516.9624557  1024523.40   552670.76    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3F2_6F
 10  2  1/2 +   -1514.9211333  1472541.88   448018.48    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3F2_6F
 .........
```

The "energy total" of the second result obtained for calculation is significantly lower than the value indicated in the manual. Conversely, when using the same rcsf.inp file (first result) for performing the identical calculation, the outcome remains incorrect.
I want to know what the problem is and how to fix it. 

Thank you for taking the time to read my question, and I would appreciate it if you could give me a little help.

Have a nice day!

**Comment by WenxianLi** [comment]
Hi,
Generally, if the code compiles successfully, the problem you described is not expected. Could you please make sure that:
1. The script/command/input files are exactly identical for your two runs.
2. Make sure you did a fresh compile from the very beginning(start a new compilation with make clean), which means you didn't not mix any of the existing object files (.o files from the old version of gcc, etc) as well as mod file (mod) within the build. AFAIK, if that happens it might lead to your problem.  Also, beware of the existing libraries such as LAPACK/BLAS, if they are not proper upgrade, things would occurs, either. 

Best,
wx

**Comment by tspejo** [comment]
Dear Jinzhe

Thank you for reporting these problems.

To deal with them, you should go to the librang90 library and make the changes in diaga1 to diaga5 (see below)
so that IAT has the intent(inout)

Make these changes and recompile the full package and try your reported cases again.

Please let us know if this solved your problems or if there are remaining issues.

Best wishes
Gedimnas Gaigalas and Per Jönsson


librangular:



------

DIAGA1

------

      INTEGER, INTENT(INOUT)      :: IAT

------

DIAGA2

------

      INTEGER, INTENT(INOUT)      :: IAT

------

DIAGA3

------

      INTEGER, INTENT(INOUT)      :: IAT

------

DIAGA4

------

      INTEGER, INTENT(INOUT)      :: IAT

------

DIAGA5

------

      INTEGER, INTENT(INOUT)      :: IAT

________________________________
From: JinzheZhang ***@***.***>
Sent: Wednesday, December 13, 2023 3:42 PM
To: compas/grasp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [compas/grasp] Compile issues by gcc-13 (Issue #112)


Hi everyone

I meet a issues when using grasp, which compiled by gcc-13.

The server of my teammate was recently upgraded from Fedora 37 to 39. In Fedora 39, the default GCC compilation is gcc-13. We were able to successfully compile Grasp; however, we noticed some discrepancies between the example in the manual (6.5. Fifth Example: The Study of Energy Spectra for Ni XIV, Obtaining Unique Labels) and our own results.

1. rcsfinteract

We get different results from rcsfinteract with same command:

  1.  the result get from gcc-11 version, which is the same with the manual

 RCSFinteract: Determines all the CSFs (rcsf.inp) that interact
               with the CSFs in the multireference (rcsfmr.inp)
               (C)  Copyright by G. Gaigalas and Ch. F. Fischer
               (Fortran 95 version)               NIST  (2021).
               Input files: rcsfmr.inp, rcsf.inp
               Output file: rcsf.out

 Reduction based on Dirac-Coulomb (1) or
 Dirac-Coulomb-Breit (2) Hamiltonian?
2
 Loading Configuration Symmetry List File ...
 There are 16 relativistic subshells;
  Block    MR NCSF   Before NCSF   After NCSF
    1            8         1664         1047
    2           11         2837         1862
    3           10         3271         2112
    4            5         2972         1537
    5            2         2264          801

 Wall time:
        1 seconds

 Finish Date and Time:
   Date (Yr/Mon/Day): 2023/12/13
   Time (Hr/Min/Sec): 19/30/02.690
   Zone: +0800

 RCSFinteract: Execution complete.

  1.  the result get from gcc-13 version

 RCSFinteract: Determines all the CSFs (rcsf.inp) that interact
               with the CSFs in the multireference (rcsfmr.inp)
               (C)  Copyright by G. Gaigalas and Ch. F. Fischer
               (Fortran 95 version)               NIST  (2021).
               Input files: rcsfmr.inp, rcsf.inp
               Output file: rcsf.out

 Reduction based on Dirac-Coulomb (1) or
 Dirac-Coulomb-Breit (2) Hamiltonian?
2
 Loading Configuration Symmetry List File ...
 There are 16 relativistic subshells;
  Block    MR NCSF   Before NCSF   After NCSF
    1            8         1664         1142
    2           11         2837         2058
    3           10         3271         2362
    4            5         2972         1770
    5            2         2264          909

 Wall time:
        1 seconds

 Finish Date and Time:
   Date (Yr/Mon/Day): 2023/12/13
   Time (Hr/Min/Sec): 19/32/43.439
   Zone: +0800

 RCSFinteract: Execution complete.


2. rmchdf and rci

I applied the identical procedure as that of manual operation and obtained the following outcome:

1.the result get from gcc-11 version, which is the same with the manual

------------------------------------------------------------------------------------------
No  Pos  J   Parity  Energy Total  Levels          Splitting     Configuration
                      (a.u.)        (cm^-1)         (cm^-1)
------------------------------------------------------------------------------------------
1   1  3/2     -    -1443.2224318       0.00            0.00    2s(2).2p(6).3s(2).3p(3)4S3_4S
2   2  3/2     -    -1443.0055953   47590.12        47590.12    2s(2).2p(6).3s(2).3p(3)2D3_2D
3   1  5/2     -    -1442.9699841   55405.86         7815.74    2s(2).2p(6).3s(2).3p(3)2D3_2D
4   1  1/2     -    -1442.8231291   87636.81        32230.95    2s(2).2p(6).3s(2).3p(3)2P1_2P
5   3  3/2     -    -1442.7718374   98894.05        11257.25    2s(2).2p(6).3s(2).3p(3)2P1_2P
6   1  5/2     +    -1441.7819193  316155.95       217261.89    2s(2).2p(6).3s_2S.3p(4)3P2_4P
7   1  3/2     +    -1441.7163490  330546.97        14391.02    2s(2).2p(6).3s_2S.3p(4)3P2_4P
8   1  1/2     +    -1441.6893375  336475.31         5928.35    2s(2).2p(6).3s_2S.3p(4)3P2_4P
9   2  3/2     +    -1441.4303647  393313.26        56837.95    2s(2).2p(6).3s_2S.3p(4)1D2_2D
10  2  5/2     +    -1441.4141226  396877.99         3564.73    2s(2).2p(6).3s_2S.3p(4)1D2_2D
 .........

  1.  the result get from gcc-13 version

rlevels Ni_even_n4.cm Ni_odd_n4.cm
 nblock =            5   ncftot =         8241   nw =           16   nelec =           15
 nblock =            3   ncftot =         1352   nw =           16   nelec =           15

 Energy levels for ...
 Rydberg constant is   109737.31569
 Splitting is the energy difference with the lower neighbor
------------------------------------------------------------------------------------------
 No Pos  J Parity Energy Total    Levels     Splitting     Configuration
                      (a.u.)      (cm^-1)     (cm^-1)
------------------------------------------------------------------------------------------
  1  1  5/2 +   -1521.6305278        0.00        0.00    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3P2_6D
  2  1  7/2 +   -1521.5555329    16459.47    16459.47    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3P2_6D
  3  1  3/2 +   -1521.3337119    65143.56    48684.09    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3P2_6P
  4  1  1/2 +   -1520.1621637   322268.67   257125.11    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3P2_4P
  5  2  5/2 +   -1519.9963675   358656.72    36388.05    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3P2_4D
  6  2  7/2 +   -1519.8619203   388164.47    29507.76    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3F2_4G
  7  2  3/2 +   -1519.7382993   415296.15    27131.67    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3F2_6F
  8  1  9/2 +   -1519.4806089   471852.64    56556.49    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3F2_6G
  9  3  5/2 +   -1516.9624557  1024523.40   552670.76    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3F2_6F
 10  2  1/2 +   -1514.9211333  1472541.88   448018.48    2s(2).2p(6).3s_2S.3p(2)3P2_4P.3d(2)3F2_6F
 .........

The "energy total" of the second result obtained for calculation is significantly lower than the value indicated in the manual. Conversely, when using the same rcsf.inp file (first result) for performing the identical calculation, the outcome remains incorrect.
I want to know what the problem is and how to fix it.

Thank you for taking the time to read my question, and I would appreciate it if you could give me a little help.

Have a nice day!

**Comment by tspejo** [comment]
Dear Per,
Dear Jinzhe,

Please find the subroutines which you need to substitute the old ones with in the librang90 (directory GRASP-2018\src\lib\librang90).
In this case we will not have any problems with gfortran V13, too.

Best wishes,
Gediminas

**Comment by jinzhezhang020** [comment]
Dear Gedimnas Gaigalas and Per Jönsson:

     Thank you for your reply.According to your description, I made changes to the librang90 library and modified diaga1 to diaga5 so that IAT has the intent(inout). Then, i recompiled twice using gfortran-13, with each compilation process using the system’s original LAPACK, BLAS library (3.11.0-5), and MKL library (version 2024), respectively. Before each compilation, i used the make clean command to clean the compilation environment. Finally, i ran the compiled program according to the example in the manual (6.5. Fifth Example), but the results were still the same as before.

**Comment by jinzhezhang020** [comment]
Dear Wenxian,
Thank you for your response. Based on your comment, i can confirm that the script/command/input files were exactly identical for both runs. Additionally, i did use the make clean command before compiling, and during the previous compilation process, i consistently used the LAPACK/BLAS library (3.11.0-5). Later, i modified the librang90 library and changed diaga1 to diaga5 so that IAT has the intent(inout). After that, i recompiled twice using gfortran-13, with each compilation process using the system’s original LAPACK/BLAS library (3.11.0-5), and MKL library (version 2024), respectively. Before each compilation, i used the make clean command to clean the compilation environment. Finally, i ran the compiled program according to the example in the manual (6.5. Fifth Example), but the results were still the same as before.

**Comment by jinzhezhang020** [comment]
Dear Gedimnas Gaigalas and Per Jönsson,
I'm glad to receive your reply! That helps me a lot.
According to your description, I made changes to the librang90 library and modified diaga1.f90 to diaga5.f90 and diaga1_I.f90 to diaga5_I.f90 so that IAT has the intent(inout). Then, I used the make clean command to clean the compilation environment and recompiled the package. Finally, I got exactly the same result as in the manual.
With best regards,
Jinzhe

**Comment by jinzhezhang020** [comment]
Dear Wenxian,
Thank you for your reply.
I made changes to the librang90 library and modified diaga1.f90 to diaga5.f90 and diaga1_I.f90 to diaga5_I.f90 so that IAT has the intent(inout). Then, I got exactly the same result as in the manual.
With best regards,
Jinzhe

**Comment by WenxianLi** [comment]
@jinzhezhang020 Great！Glad to know the problem is solved.
