### ISSUE TITLE
Configuration for the compiler

### ISSUE THREAD

**Issue by QuantumGuy** [compas/grasp#22]
In the script _make_environment_gfortran_,   

> export FC_MPI="mpifort" 

 seems should be changed to something like 
> export FC_MPI="mpif90"

**Comment by jongrumer** [comment]
Hi Xiaobing,

No, I don't think it should actually :) - mpif90 and mpif77 are legacy wrapper which are deprecated since OpenMPI v 1.7 (we're now at v 4.0). See the open-mpi doc below, section 2, for more details. In short mpif90 or mpif77 anyway just calls mpifort which is a general wrapper which compiles any type of fortran dialect (wether modern fortran or old-style f77 code), and they will, if they haven't already,  be removed in future releases of open-mpi.

https://www.open-mpi.org/faq/?category=mpi-apps#mpifort-vs-mpif77-and-mpif90

Cheers,
Jon

**Comment by QuantumGuy** [comment]
Hi，Jon

Thank you very much for your explanation. 
I didn't realize the development of the OpenMPI. And I  thought mpifort by the name is something from the Intel Fortran compiler.  Finally, I realize that mpifort is the new name for the Fortran OpenMPI compiler. 

Thank you very much for the explanation. 

Cheers,
Xiaobin

**Comment by jongrumer** [comment]
No problem :)
