### ISSUE TITLE
jj2lsj Level Index Limitations

### ISSUE THREAD

**Issue by StevenBromley** [compas/grasp#48]
To whom it may concern,

I am running some CSF files from FAC through Grasp's jj2lsj module. It seems that the jj2lsj outputs "*.uni.lsj.lbl" cannot print out triple-digit level indexes, only single and double digit levels. Triple digit level indexes are denoted with "**". Is there a workaround for this issue?

**Comment by jongrumer** [comment]
Hi Steven! Thanks for your message!

Yes we are aware of this - "large-case" versions of the codes supporting +99 eigenstates simultaneously are in testing phase, and this should hopefully be added to master within a not too long time. Keep an eye out for updates on master. And meanwhile you can try to edit the jj2lsj print out for the sake of using it with FAC, but be aware of that altering the format will prohibit other parts of grasp to read the files properly - i.e. the transition codes. 

And since you use FAC, please make sure you reference grasp in your work, and in particular jj2lsj - a lot of hard work has gone into the development of these codes. I'm sure you do, just many that forget.

Cheers,
Jon / Uppsala University

**Comment by StevenBromley** [comment]
Hi Jon,

Thank you for the response! I am glad to hear that the solution is in testing; I will keep an eye out for the new version.

I will try to document my efforts in getting the index print w/ length 3 working; most likely I will just clone the grasp branch and recompile a separate version with my changes included. That should be a workaround for now.

Thanks again for everyone working on this; jj2lsj is a very powerful (and helpful) code, so I'll be sure to reference appropriately!

Best wishes,
Steve

**Comment by StevenBromley** [comment]
Dear all,

I've found a workaround for this problem. On line 1710 of jj2lsj_code.f90, change 'I2' to 'I3' in the write(57) statement and recompile. For some reason unknown to me, the executable in /build/bin/ does not appear to be affected by this change, but the executable in /bin/ does. I am closing this ticket.

Best wishes,
Steve
